1b: 1b.cpp bellmanFord.cpp
	g++ -o 1b -O3 -std=c++11 1b.cpp bellmanFord.cpp ../Woche8/graph.cpp; ./1b

1a: 1a.cpp bellmanFord.cpp
	g++ -o 1a -O3 -std=c++11 1a.cpp bellmanFord.cpp ../Woche8/graph.cpp; ./1a
2:  2.cpp
	g++ -o 2 -O3 -std=c++11 2.cpp ../reusable_stuff/graph.cpp; ./2

clean:
	rm -f 1a; rm -f 2; rm -f 1b;
