2: 2.cpp triangle.cpp
	g++ -o 2 -O3 -std=c++11 2.cpp triangle.cpp;

1d: 1d.cpp graph.cpp
	g++ -o 1d -O3 -std=c++11 1d.cpp graph.cpp;

1c: 1c.cpp graph.cpp
	g++ -o 1c -O3 -std=c++11 1c.cpp graph.cpp;

1b: 1b.cpp graph.cpp
	g++ -o 1b -O3 -std=c++11 1b.cpp graph.cpp;

1a: 1a.cpp graph.cpp
	g++ -o 1a -O3 -std=c++11 1a.cpp graph.cpp;

all: 1a 1b 1c 1d 2
